name: Send LINE Menu

on:
  schedule:
    - cron: "0 3 * * *"   # 毎日 3:00 (UTC) に実行 → 日本時間12:00
  workflow_dispatch:
    inputs:
      message:
        description: 'LINEからのメッセージ'
        required: false

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          RAKUTEN_APP_ID: ${{ secrets.RAKUTEN_APP_ID }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python main.py
